### ISSUE TITLE
couldn't find file 'spree/frontend/spree_my_favourites'

### ISSUE THREAD

**Issue by paul1113** [vinsol-spree-contrib/spree_favorite_products#1]
hi friend,
              when i use the "spree_my_favourites" it display 
 Sprockets::FileNotFound in Spree::Home#index 
/usr/local/rvm/gems/ruby-2.1.0@spree/gems/spree_frontend-2.2.2/app/views/spree/shared/_head.html.erb where line #8 raised:
couldn't find file 'spree/frontend/spree_my_favourites'
  (in /home/paul/rails_projects/Elnath/vendor/assets/stylesheets/spree/frontend/all.css:12)
Extracted source (around line #8):
 5    <%== meta_data_tags %>
6     <%= canonical_tag(Spree::Config.site_url) %>
7     <%= favicon_link_tag image_path('favicon.ico') %>
8     <%= stylesheet_link_tag 'spree/frontend/all', :media => 'screen' %> 
9     <%= csrf_meta_tags %>
10   <%= javascript_include_tag 'spree/frontend/all' %>
11   <!--[if lt IE 9]>
can you tell me How can I solve this problem? thank you!

**Comment by nimish13** [comment]
Hi @paul1113, I was not able to replicate this issue, please let me know if you are still able to replicate this issue, in case you can, please provide full backtrace along with your Gemfile.
